from __future__ import with_statement # This isn't required in Python 2.6

flags = ['-ggdb', '-Wall', '-O0']
# flags = ['-ggdb', '-Wall', '-O3']

#gfprof
#flags = ['-ggdb', '-Wall', '-O0', '-pg' ]

env = Environment(
  CXX = 'g++',
  CCFLAGS = flags,
  CPPPATH = ['#.'],
  LIBS = ['gtest', 'pthread'],
)


env.Object(Glob('*.cpp'))
env.Object(Glob('*/*.cpp'))
# env.Object(Glob('*/*/*.cpp'))

Objects = ['string_utils.o', 'rule_parser.o', 'glu_manager.o', 'test/test_classes.o']

#env.Program('main_parser', ['main_parser'] + Objects)

env.Program('test/gtest_string_utils', ['test/gtest_string_utils'] + Objects)
env.Program('test/gtest_rule_parser', ['test/gtest_rule_parser'] + Objects)
env.Program('test/gtest_glu_manager', ['test/gtest_glu_manager'] + Objects)


